envelope:
  total_money: 10000000000
  total_envelope: 50000000
  min_money: 10
  max_money: 1000
  max_snatch: 5
mysql:
  username: root
  password: 852196
  address: 127.0.0.1:3306
  dbname: envelope
redis:
  password: 852196
  address: 127.0.0.1:6379
  max_pool_size: 2000
kafka:
