envelope:
  total_envelope: 1000000
  total_money: 1000000000
  min_money: 10
  max_money: 1000
  max_snatch: 500
mysql:
  username: root
  password: 852196
  # address: 175.27.248.24:3306
  address: 127.0.0.1:3306
  dbname: envelope
redis:
  password: 852196
  address: 127.0.0.1:6379
  max_pool_size: 2000
kafka:
